# ESP32WROM
# Display
# DISPLAY_PIN_CS=15
# DISPLAY_PIN_RST=4
# DISPLAY_PIN_DC=2
# DISPLAY_PIN_MOSI=23
# DISPLAY_PIN_SCK=18
# DISPLAY_PIN_MISO=19
# DISPLAY_PIN_LED=32

# # Charging module
# CHARGE_PIN_STAT1=25
# CHARGE_PIN_STAT2=26

# # SD card
# SD_PIN_SCK = 13
# SD_PIN_MISO = 12
# SD_PIN_MOSI = 14
# SD_PIN_CS = 27

# ESP32S3N16R8
# Display
DISPLAY_PIN_CS   = 15
DISPLAY_PIN_RST  = 16
DISPLAY_PIN_DC   = 17
DISPLAY_PIN_MOSI = 11
DISPLAY_PIN_SCK  = 12
DISPLAY_PIN_LED  = 21
DISPLAY_PIN_MISO = 13

# Charging module
CHARGE_PIN_STAT1 = 4
CHARGE_PIN_STAT2 = 5

# SD card (shared SPI bus)
SD_PIN_SCK  = 12
SD_PIN_MISO = 13
SD_PIN_MOSI = 11
SD_PIN_CS   = 10