# ESP32S3N16R8 DevC1
# Shared SPI BUS for display integrated devices
SPI_BUS_MISO = 11
SPI_BUS_SCK  = 10
SPI_BUS_MOSI = 18

# Touch screen controls (display pcb integrated)
TOUCH_PIN_IRQ = 14
TOUCH_PIN_DO = SPI_BUS_MISO
TOUCH_PIN_DIN = SPI_BUS_MOSI
TOUCH_PIN_CS = 13
TOUCH_PIN_CLK = SPI_BUS_SCK

# Display
DISPLAY_PIN_MISO = SPI_BUS_MISO # 
DISPLAY_PIN_LED  = 12
DISPLAY_PIN_SCK  = SPI_BUS_SCK
DISPLAY_PIN_MOSI = SPI_BUS_MOSI
DISPLAY_PIN_DC   = 16
DISPLAY_PIN_RST  = 15
DISPLAY_PIN_CS   = 21
# GND - GND
# VCC - 3V3


# SD card  (display pcd integrated)
SD_PIN_CS   = 17
SD_PIN_MOSI = SPI_BUS_MOSI
SD_PIN_MISO = SPI_BUS_MISO
SD_PIN_SCK  = SPI_BUS_SCK

# Charging module BQ25185
CHARGE_PIN_STAT1 = 4
CHARGE_PIN_STAT2 = 5

# GNSS module
GNSS_PIN_TX = 7
GNSS_PIN_RX = 6
# VCC - 3V3
# GND - GND

# Soft power buttom
POWER_BTM = 20
# GND - GND

# GY-21 HTU21 Humidity and Temperature Sensor
TEMP_SENSOR_SDA = 47
TEMP_SENSOR_SCL = 48
# VCC - 3V3
# GND - GND
