from .widget import Widget
from .area import AreaWidget
from .text import TextWidget
from .value import ValueWidget
from .timer import TimerWidget
from .navigation import NavigationWidget
from .alarm import AlarmWidget
from .route import RouteWidget
from .route_preview import RoutePreviewWidget
from .route_list import RouteListWidget
from .location import LocationWidget
from .elevation import ElevationWidget
from .navigation_info import NavigationInfoWidget